--- 
- 
  become: yes
  hosts: all
  name: Playbook
  tasks: 
    - 
      name: "ensure apache is at the latest version learning for Jenkins"
      yum: 
        name: httpd
        state: latest
    - 
      name: "ensure apache is running"
      service: 
        name: httpd
        state: started
        
