---
- hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: copy war file
    copy: src=/var/lib/jenkins/workspace/first-job-play-ansible/target/MavenWebApp.war dest=/opt/tomcat/webapps/
